# Generated by Django 5.1.3 on 2024-12-22 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_student_leave'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student_leave',
            new_name='Student_leave_detail',
        ),
    ]
