# Generated by Django 5.1.3 on 2024-12-22 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_student_leave_student_leave_detail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student_leave_detail',
            new_name='Student_leave',
        ),
    ]
